export const ACTION_SELECT_VARIABLE = 'SELECT_VARIABLE';
export const ACTION_DESELECT_VARIABLE = 'DESELECT_VARIABLE';

export const ACTION_FETCH_VARIABLE_DATA = 'FETCH_VARIABLE_DATA';
export const ACTION_FETCH_VARIABLE_DATA_SUCCESS = 'FETCH_VARIABLE_DATA_SUCCESS';
export const ACTION_FETCH_VARIABLE_DATA_ERROR = 'FETCH_VARIABLE_DATA_ERROR';

export const ACTION_SELECT_COHORT = 'SELECT_COHORT';
export const ACTION_DESELECT_COHORT = 'DESELECT_COHORT';

export const ACTION_FORM_SET_AGE = 'FORM_SET_AGE';
export const ACTION_FORM_SET_GENDER = 'FORM_SET_GENDER';

export const ACTION_FORM_SUBMIT = 'FORM_SUBMIT';
export const ACTION_FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const ACTION_FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR';

export const ACTION_FORM_FLUSH = 'FORM_FLUSH';

export const VARIABLE_AGE = 'age';
export const VARIABLE_GENDER = 'gender';
