version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/src
    working_dir: "/opt/src/app"
    environment:
      FLASK_APP: server.py
      FLASK_DEBUG: 1
    command: ["source activate snoek && flask run --with-threads --host=0.0.0.0"]